"use client";
import { useState } from "react";
import { useCreateImagine } from "@/lib/query/create";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import posthog from "posthog-js";
import FileUpload from "@/components/fileUpload";

export default function UploadPage() {
  const create = useCreateImagine();
  const [xHandle, setXHandle] = useState("");
  const [prompt, setPrompt] = useState("");
  const [file, setFile] = useState<File | null>(null);

  function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!file) return toast.error("Please select a file");
    posthog.capture("imagine_upload", { xHandle, prompt });
    create.mutate({ xHandle, prompt, file });
  }

  return (
    <div className="min-h-screen w-full overflow-x-hidden flex items-center justify-center px-4">
      <Button
        variant="outline"
        size="icon"
        asChild
        className="cursor-pointer fixed top-4 left-4"
      >
        <Link href="/" aria-label="Go back">
          <ArrowLeft />
        </Link>
      </Button>
      <div className="w-full max-w-sm sm:max-w-md md:max-w-lg overflow-hidden">
        <div className="w-full flex flex-col items-center justify-center">
          <div className="w-20 h-20 sm:w-24 sm:h-24 bg-primary-foreground rounded-full flex items-center justify-center">
            <svg
              className="w-16 h-16 sm:w-20 sm:h-20"
              fill="currentColor"
              fillRule="evenodd"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
              aria-label="Grok logo"
            >
              <title>Grok</title>
              <path d="M9.27 15.29l7.978-5.897c.391-.29.95-.177 1.137.272.98 2.369.542 5.215-1.41 7.169-1.951 1.954-4.667 2.382-7.149 1.406l-2.711 1.257c3.889 2.661 8.611 2.003 11.562-.953 2.341-2.344 3.066-5.539 2.388-8.42l.006.007c-.983-4.232.242-5.924 2.75-9.383.06-.082.12-.164.179-.248l-3.301 3.305v-.01L9.267 15.292M7.623 16.723c-2.792-2.67-2.31-6.801.071-9.184 1.761-1.763 4.647-2.483 7.166-1.425l2.705-1.25a7.808 7.808 0 00-1.829-1A8.975 8.975 0 005.984 5.83c-2.533 2.536-3.33 6.436-1.962 9.764 1.022 2.487-.653 4.246-2.34 6.022-.599.63-1.199 1.259-1.682 1.925l7.62-6.815"></path>
            </svg>
          </div>
          <div className="flex flex-col items-center justify-center mt-6 text-center">
            <h1 className="text-2xl sm:text-3xl font-bold">
              Upload your imagine
            </h1>
            <p className="text-sm text-muted-foreground mb-6">
              Upload an image or video generated by Grok to the Grok Imagine Art
              Contest.
            </p>
          </div>
        </div>
        <form onSubmit={onSubmit} className="w-full space-y-4">
          <div className="flex flex-col">
            <Input
              className="w-full bg-input text-sm rounded-md px-3 py-2 border border-border"
              placeholder="X Handle (truly_sn)"
              value={xHandle}
              onChange={(e) => setXHandle(e.target.value)}
              required
            />
            <sub className="text-xs sm:text-sm text-muted-foreground">
              Enter your X handle username or handle only eg:(truly_sn)
            </sub>
          </div>
          <Textarea
            className="w-full min-h-24"
            placeholder="Prompt"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            required
          />
          <div className="w-full">
            <FileUpload onChange={(file) => setFile(file)} />
          </div>
          <Button type="submit" className="w-full">
            {create.isPending ? "Uploading..." : "Create"}
          </Button>
        </form>
      </div>
    </div>
  );
}
